# Generated by Django 6.0.2 on 2026-02-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="username",
                        max_length=100,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        db_column="first_name",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        db_column="last_name",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="phone",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_column="is_active", default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="Дата регистрации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Отправлено"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                            ("deleted", "Удалено"),
                        ],
                        db_column="status",
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="submitted_at",
                        null=True,
                        verbose_name="Дата отправки",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="completed_at",
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "total_consumption",
                    models.DecimalField(
                        blank=True,
                        db_column="total_consumption",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Общий расход",
                    ),
                ),
                (
                    "amount_to_pay",
                    models.DecimalField(
                        blank=True,
                        db_column="amount_to_pay",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма к оплате",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, db_column="comment", verbose_name="Комментарий"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests",
                        to="meters.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="WaterMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(db_column="address", max_length=255, verbose_name="Адрес"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_column="serial_number",
                        max_length=50,
                        unique=True,
                        verbose_name="Заводской номер",
                    ),
                ),
                (
                    "meter_type",
                    models.CharField(
                        choices=[("HOT", "ГВС"), ("COLD", "ХВС")],
                        db_column="meter_type",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "meter_model",
                    models.CharField(db_column="meter_model", max_length=100, verbose_name="Модель"),
                ),
                (
                    "installation_date",
                    models.DateField(db_column="installation_date", verbose_name="Дата установки"),
                ),
                (
                    "initial_reading",
                    models.IntegerField(
                        db_column="initial_reading",
                        default=0,
                        verbose_name="Начальные показания",
                    ),
                ),
                (
                    "last_verified_reading",
                    models.IntegerField(
                        db_column="last_verified_reading",
                        default=0,
                        verbose_name="Последние показания",
                    ),
                ),
                (
                    "last_reading_date",
                    models.DateField(
                        blank=True,
                        db_column="last_reading_date",
                        null=True,
                        verbose_name="Дата последних показаний",
                    ),
                ),
                (
                    "next_verification_date",
                    models.DateField(
                        blank=True,
                        db_column="next_verification_date",
                        null=True,
                        verbose_name="Дата следующей поверки",
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        db_column="photo_url",
                        null=True,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "setup_video_url",
                    models.URLField(
                        blank=True,
                        db_column="setup_video_url",
                        null=True,
                        verbose_name="Видео",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_column="is_active", default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="updated_at",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="meters",
                        to="meters.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Счетчик",
                "verbose_name_plural": "Счетчики",
                "db_table": "water_meters",
            },
        ),
        migrations.CreateModel(
            name="ReadingPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_reading",
                    models.IntegerField(db_column="current_reading", verbose_name="Текущие показания"),
                ),
                (
                    "consumption",
                    models.IntegerField(db_column="consumption", verbose_name="Расход"),
                ),
                (
                    "reading_photo_url",
                    models.URLField(
                        blank=True,
                        db_column="reading_photo_url",
                        null=True,
                        verbose_name="Фото показаний",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="positions",
                        to="meters.request",
                    ),
                ),
                (
                    "water_meter",
                    models.ForeignKey(
                        db_column="water_meter_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="readings",
                        to="meters.watermeter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция",
                "verbose_name_plural": "Позиции",
                "db_table": "reading_positions",
            },
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["user", "status"], name="requests_user_id_2e1dfa_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["-created_at"], name="requests_created_7f688f_idx"),
        ),
        migrations.AddIndex(
            model_name="watermeter",
            index=models.Index(fields=["user", "address"], name="water_meter_user_id_3c5f54_idx"),
        ),
        migrations.AddIndex(
            model_name="watermeter",
            index=models.Index(fields=["serial_number"], name="water_meter_serial__d9e6c4_idx"),
        ),
        migrations.AddIndex(
            model_name="readingposition",
            index=models.Index(fields=["request", "water_meter"], name="reading_pos_request_73ccf7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="readingposition",
            unique_together={("request", "water_meter")},
        ),
    ]
