# Generated by Django 4.2.30 on 2026-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_user_last_login_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
