# Generated by Django 4.2.30 on 2026-05-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0005_remove_user_last_login_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_column='account_number', max_length=50, unique=True, verbose_name='Номер лицевого счёта')),
                ('address', models.CharField(db_column='address', max_length=255, verbose_name='Адрес')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='meters.user')),
            ],
            options={
                'verbose_name': 'Лицевой счёт',
                'verbose_name_plural': 'Лицевые счета',
                'db_table': 'personal_accounts',
            },
        ),
        migrations.AddField(
            model_name='watermeter',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='meters', to='meters.personalaccount'),
        ),
    ]
