# Generated by Django 4.2.30 on 2026-05-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_personalaccount_watermeter_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watermeter',
            name='water_meter_user_id_3c5f54_idx',
        ),
        migrations.RemoveField(
            model_name='watermeter',
            name='user',
        ),
    ]
